helmChartInflationGenerator:
- chartName: metallb
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: v2.5.6
  releaseName: metallb
  releaseNamespace: operations
  values: https://raw.githubusercontent.com/pdorczuk-kubeshield/cluster-apps/master/apps/metallb/metallb-values.yaml

commonLabels:
  application: ingress
  component: metallb
  team: operations
namespace: operations