apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCCkYQ5SMegZzKcR3CW30x98goPe+VP5S/Djf2YvJrd8y1A3j4jJI/cJ2t0lvZJ6Y+3+c14QSSBUCIYe4vYyLH7HBGr4C5rbvWIW4wF4woedg/wtK/qUakujNhiLj9GZxERMvWIbPTJLWonN7v6PYNVA0XbWEpZybWQTgx094xC5F7m9Xq/eo6ktzALhZKXRDUwyI6zHE0Y5D5A4vEj5bJypsxklBwOsDsykwPJVVRWUmCjEK1nf41WpdLxYj3slVwanBQdgCDggw0ukSJYs3b4YEfBszlibUBnYX0MtVAga+ZNwLTquRkuEwZPuwbmrQuz1WmpXxDKbNDGjh8+mw/YxD1rG01TxXwEpVRihEuHDKkdwcJEBHGh6NQVpEBn491NkMn6T+EMkM2Hqee1YgrJFPYO8QeLaPtfN0cpmXC54rLY3JkSN4TEW+OXpNbQsSbKct5zkWELHqWLexN+k0KBbSxMavo+d5MjvwuxnZZi9SLsQOqDc9HedqeRA9YMvpRtXEQSJKMwNyPD54Oa4wHMSw9gXHcr33F019ozcSe2ZAzPqjfdAPPpEQF8lLqlOnfEqEwDml2J6lvbxdO/nDio6VldqXqtmV460ZQF+TK9Nb6qBEhxS/yklOiX796iXaxv7nTl3M3J/wCD5jUDHcMGiUz+GDAcuoHxvouNbPWR4htrB6GL8tk48kdaVRILfAUOJ09XDfpZ08crge+96HOR8FWQ0CCoSB/gYF1qMCewt/ih8t49LglR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

