helmChartInflationGenerator:
- chartName: kyverno-policies
  chartRepoUrl: https://kyverno.github.io/kyverno/
  chartVersion: v2.1.0
  releaseName: kyverno-policies
  releaseNamespace: security
  values: https://raw.githubusercontent.com/pdorczuk-kubeshield/kube-system-apps/master/kyverno/kyverno_policies-values.yaml
  extraArgs:
  - --include-crds

resources:
- github.com/pdorczuk-kubeshield/kubeshield-policies//policies
- namespace.yaml

commonLabels:
  team: operations
namespace: operations