apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: pdorczuk@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret used to store the account's private key.
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: pdorczuk@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsNames:
          - 'kubeshield.com'
          - '*.kubeshield.com'
        dnsZones:
          - 'kubeshield.com'